language: node_js

node_js:
  - "node"

cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache

before_script:
  - yarn

script: yarn build

after_success:
  - node_modules/.bin/surge -p ./build/ -d https://norocketlab.surge.sh
  - node_modules/.bin/surge -p ./build/ -d https://norocketlab.net

